name: Deploy

on:
 workflow_dispatch:
    inputs:
        allegroversion:
          default: "5.2.8.0"
          description: "Allegro 5"
        zlibversion:
            default: "1.3"
            description: "Zlib"
        libpngversion:
            default: "1.6.40"
            description: "LibPNG"
        freetypeversion:
            default: "2.12.1"
            description: "FreeType"
        liboggversion:
            default: "1.3.5"
            description: "Lib OGG"
        libvorbsversion:
            default: "1.3.7"
            description: "Lib Vorbis"
        flacversion:
            default: "1.3.4"
            description: "Flac"
        physfsversion:
            default: "3.0.2"
            description: "Physfs"
    
jobs:
  build:
    name: Allegro v${{ github.event.inputs.allegroversion }}
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Deploy
        run: |
            make build push \
            ALLEGRO_VERSION=${{ github.event.inputs.allegroversion }} \
            ZLIB_VERSION=${{ github.event.inputs.zlibversion }} \
            LIBPNG_VERSION=${{ github.event.inputs.libpngversion }} \
            FREETYPE_VERSION=${{ github.event.inputs.freetypeversion }} \
            LIBOGG_VERSION=${{ github.event.inputs.liboggversion }} \
            LIBVORBIS_VERSION=${{ github.event.inputs.libvorbisversion }} \
            FLAC_VERSION=${{ github.event.inputs.flacversion }} \
            PHYSFS_VERSION=${{ github.event.inputs.physfsversion }} \



